package com.dmdev.jdbc.starter;

import com.dmdev.jdbc.starter.util.ConnectionManager;
import org.postgresql.Driver;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class JdbcRunner {
    public static void main(String[] args) throws SQLException {

        Class<Driver> driverClass = Driver.class;

        String sql = """
                INSERT INTO info(data)
                VALUES 
                ('autogenerated')
                """;
        try (var connection = ConnectionManager.open();
             var statement = connection.createStatement()) {
            System.out.println(connection.getSchema());
            System.out.println(connection.getTransactionIsolation());
            var executeResult = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            final var generatedKeys = statement.getGeneratedKeys();
            if(generatedKeys.next()){
                final var generatedKeysInt = generatedKeys.getInt(1);
                System.out.println(generatedKeysInt);
            }
        }

    }
}
